### ISSUE TITLE
Please support a CACHE_DIR env var

### ISSUE THREAD

**Issue by hulkish** [zertosh/v8-compile-cache#16]
I would like to archive and then re-use the cache between ci builds. Currently, the cache location is only chosen via `os.tmpdir()`.

I'd like to be able to override this behavior via env var.

**Comment by hulkish** [comment]
hoping if i could please get an update on this?

**Comment by simlu** [comment]
Any update on this?

**Comment by simlu** [comment]
Added a pr here: https://github.com/zertosh/v8-compile-cache/pull/18/files

**Comment by ganapativs** [comment]
Any updates here? Can we support this please?

**Comment by zertosh** [comment]
v8-compile-cache@2.2.0 now has an `V8_COMPILE_CACHE_CACHE_DIR` env.
