### ISSUE TITLE
Buffer is undefined

### ISSUE THREAD

**Issue by S--Minecraft** [zertosh/v8-compile-cache#3]
https://nodejs.org/api/buffer.html

`The Buffer class is a global within Node.js, making it unlikely that one would need to ever use require('buffer').Buffer.`

Contrary to this, it needs "require" to use.

**Comment by zertosh** [comment]
I'm ok with this assumption

**Comment by xinnian88** [comment]
// create wrapper function
    var content1 = `var Buffer = global.Buffer; {
      ${content}
    };`;
    var wrapper = Module.wrap(content1);


change Content By this, maybe work.  define a  custom Buffer

test on node 10.15.0
