### ISSUE TITLE
process.mainModule has been deprecated since v14.0.0

### ISSUE THREAD

**Issue by roland-reed** [zertosh/v8-compile-cache#33]
`process.mainModule` has been deprecated since v14.0.0, while it is still being used here: https://github.com/zertosh/v8-compile-cache/blob/master/v8-compile-cache.js#L176, and here is the document of Node.js: https://nodejs.org/api/process.html#process_process_mainmodule

**Comment by zertosh** [comment]
Fixed in v8-compile-cache@2.3.0 by #34
